# Generated by Django 5.0.7 on 2024-10-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0008_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
    ]
